name: Publish Docker Image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from VERSION file
        id: get_version
        run: echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t sgt .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Tag Docker image
        run: |
          docker tag sgt ${{ secrets.DOCKER_USERNAME }}/sgt:latest
          docker tag sgt ${{ secrets.DOCKER_USERNAME }}/sgt:${{ env.VERSION }}
          docker tag sgt ${{ secrets.DOCKER_USERNAME }}/sgt:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sgt:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sgt:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/sgt:${{ github.sha }}

      - name: Clean up
        run: docker system prune -f
